### ISSUE TITLE
It does not run under WindowsXP

### ISSUE THREAD

**Issue by sblendorio** [RobSmithDev/ArduinoFloppyDiskReader#17]
Launching the EXE file, this dialog is raised:
![image](https://user-images.githubusercontent.com/2118813/111171582-5b223a80-85a5-11eb-8e76-991ea2b1138f.png)

("it's not a valid Win32 application")

**Comment by RobSmithDev** [comment]
Hi

It wasn’t compiled to run under windows XP. If you want to run it on there you will have to re-compile it yourself.  The source code is available to do so

Best wishes

Rob Smith
Creative/Frontend/Backend Developer
http://robsmithdev.co.uk

**Comment by sblendorio** [comment]
Which compiler should I use under Windows XP?

Thanks in advance

**Comment by sblendorio** [comment]
Using Visual Studio Community with proper build tools

**Comment by sblendorio** [comment]
Here is the EXE compatible with Windows XP: https://www.dropbox.com/s/kp4kt5jmccn946o/ArduinoFloppyReaderWinXP.zip?dl=0
