### ISSUE TITLE
Writting .d81 files

### ISSUE THREAD

**Issue by rdpeake** [RobSmithDev/ArduinoFloppyDiskReader#18]
Hi Rob,

I have seen the linked repo: https://github.com/hpingel/pyAccess1581 but can only see read usages there and was wondering if your repo has support for writing d81 image files to a disk in the 1581 supported format or if i need to be making a request on that repo for writing 1581.

Thanks for writing this software and hardware combination,

Thanks, 
Russell

**Comment by RobSmithDev** [comment]
Hi,

No I have nothing for these so best to contact them

Best wishes 

Rob Smith
Creative/Frontend/Backend Developer
http://robsmithdev.co.uk
