### ISSUE TITLE
How to write on a sector

### ISSUE THREAD

**Issue by cedricp** [RobSmithDev/ArduinoFloppyDiskReader#31]
Hi, I'm working on a small utility to convert disks to ADF format and read amiga filesystem with the help of ADFlib (https://github.com/lclevy/ADFlib/tree/master) and ImGui (MinGW and Linux). Reading disk works great, but I'm wondering if it's possible to write a unique sector on disk or if I should read the whole track, modify the sector, then write all.
My repo is there : https://github.com/cedricp/adfutils
Best regards

**Comment by RobSmithDev** [comment]
HiSorry for the slow reply. With Amiga sectors you have to write the entire track as it would be very difficult to write individual sectors like you can with PC disks. It does mean to do it nicely you probably want to be a little more cleaver about when you choose to writeBest wishesRobOn 22 May 2024, at 09:03, Cedric PAILLE ***@***.***> wrote:﻿
Hi, I'm working on a small utility to convert disks to ADF format and read amiga filesystem with the help of ADFlib (https://github.com/lclevy/ADFlib/tree/master) and ImGui (MinGW and Linux). Reading disk works great, but I'm wondering if it's possible to write a unique sector on disk or if I should read the whole track, modify the sector, then write all.
My repo is there : https://github.com/cedricp/adfutils
Best regards
